harvest:
  account: my-company
  username: bugyield@mycompany.com
  password: 1234
  ssl: true
  daysback: 7
bugyield:
  email_from: bugyield@mycompany.com
  email_fallback: bugyield@mycompany.com
fogbugz:
  url: https://mycompany.fogbugz.com
  username: bugyield@mycompany.com
  password: abcd
  projects: "alias,name,id"
jira:
  accout: my-company
  username: my-username
  password: 5678
  projects: "alias,name,id"
