harvest:
  account: my-company
  username: bugyield@mycompany.com
  password: 1234
  ssl: true
  daysback: 7
bugyield:
  email_from: bugyield@mycompany.com
  email_fallback: bugyield@mycompany.com
a-label:
  bugtracker: fogbugz
  url: https://mycompany.fogbugz.com
  username: bugyield@mycompany.com
  password: abcd
  projects: "alias,name,id"
another-label:
  bugtracker: jira
  url: https://mycompany.atlassian.net
  username: my-username
  password: 5678
  projects: "alias,name,id"
yet-another-label:
  bugtracker: jira
  url: https://othercompany.atlassian.net
  username: other-username
  password: 1234
  projects: "alias,name,id"
