harvest:
  account: my-company
  username: bugyield@mycompany.com
  password: 1234
  ssl: true
  daysback: 7
bugyield:
  email_from: bugyield@mycompany.com
  email_fallback: bugyield@mycompany.com
a-label:
  bugtracker: fogbugz
  url: https://mycompany.fogbugz.com
  url_ticket_pattern: /default.asp?%s #path to ticket via ID, will be prefixed with url
  username: bugyield@mycompany.com
  password: abcd
  projects: "alias,name,id"
another-label:
  bugtracker: jira
  url: https://mycompany.atlassian.net
  url_ticket_pattern: /%s #path to ticket via ID, will be prefixed with url
  username: my-username
  password: 5678
  projects: "alias,name,id"
yet-another-label:
  bugtracker: jira
  url: https://othercompany.atlassian.net
  url_ticket_pattern: /%s #path to ticket via ID, will be prefixed with url
  username: other-username
  password: 1234
  # alternative syntax for easier reading
  projects:
    - project-one-alias
    - project-two-alias
    - project-three-alias
