harvest:
  account: my-company
  username: bugyield@mycompany.com
  password: 1234
  ssl: true
  projects: "alias,name,id"
  daysback: 7
fogbugz:
  url: https://mycompany.fogbugz.com
  username: bugyield@mycompany.com
  password: abcd
bugyield:
  email_from: bugyield@mycompany.com
  email_fallback: bugyield@mycompany.com