harvest:
  account: my-company
  username: bugyield@mycompany.com
  password: 1234
  ssl: true
  daysback: 7
bugyield:
  email_from: bugyield@mycompany.com
  email_fallback: bugyield@mycompany.com
a-label:
  bugtracker: fogbugz
  url: https://mycompany.fogbugz.com
  # FogBugz specific path to ticket via ID and EventID, will be prefixed with "url". OPTIONAL, leave empty for default.
  url_ticket_pattern: '/default.asp?%1$s#BugEvent.%2$d'
  username: bugyield@mycompany.com
  password: abcd
  projects: "alias,name,id"
  email_notify_on_error: "bugyield+errors@company.com"
another-label:
  bugtracker: jira
  url: https://mycompany.atlassian.net
  # JIRA specific path to ticket via ID and WorklogID, will be prefixed with "url". OPTIONAL, leave empty for default.
  url_ticket_pattern: '/browse/%1$s?focusedWorklogId=%2$d&page=com.atlassian.jira.plugin.system.issuetabpanels%3Aworklog-tabpanel#worklog-%2$d'
  username: my-username
  password: 5678
  projects: "alias,name,id"
  email_notify_on_error: "bugyield+errors@company.com"  
yet-another-label:
  bugtracker: jira
  url: https://othercompany.atlassian.net
  # JIRA specific path to ticket via ID and WorklogID, will be prefixed with "url". OPTIONAL, leave empty for default.
  url_ticket_pattern: '/browse/%1$s?focusedWorklogId=%2$d&page=com.atlassian.jira.plugin.system.issuetabpanels%3Aworklog-tabpanel#worklog-%2$d'
  username: other-username
  password: 1234
  # alternative syntax for easier reading
  projects:
    - project-one-alias
    - project-two-alias
    - project-three-alias
  email_notify_on_error: "bugyield+errors@company.com"
